export const ROUTES = {
  LOGIN: '/login',
  PORTAL: '/',
  COMMON: {
    ROOT: '/common',
    AUTH_GROUP: '/common/auth-group',
    CODE_MGMT: '/common/code-mgmt',
    BOARD: '/common/board',
    MENU_MGMT: '/common/menu-mgmt',
    APPROVAL: '/common/approval',
    SYSTEM_MGR: '/common/system-mgr',
    ACCESS_LOG: '/common/access-log',
    ERROR_LOG: '/common/error-log',
    MESSAGE_MGMT: '/common/message-mgmt',
  },
  SYS01: { ROOT: '/sys01' },
  SYS02: { ROOT: '/sys02' },
  SYS03: { ROOT: '/sys03' },
  SYS04: { ROOT: '/sys04' },
  SYS05: { ROOT: '/sys05' },
  SYS06: { ROOT: '/sys06' },
  SYS07: { ROOT: '/sys07' },
  SYS08: { ROOT: '/sys08' },
  SYS09: { ROOT: '/sys09' },
  SYS10: { ROOT: '/sys10' },
  SYS11: { ROOT: '/sys11' },
  SYS12: { ROOT: '/sys12' },
  SYS13: { ROOT: '/sys13' },
  SYS14: { ROOT: '/sys14' },
  SYS15: { ROOT: '/sys15' },
  SYS16: { ROOT: '/sys16' },
  SYS17: { ROOT: '/sys17' },
  SYS18: { ROOT: '/sys18' },
} as const
